### ISSUE TITLE
Some of the sample data is invalid

### ISSUE THREAD

**Issue by idubrov** [smart-on-fhir/generated-sample-data#4]
Some of the data does not pass FHIR validation. Examples:

1. Bundle.entry[2].resource.ofType(Encounter).reason -- [Encounter.reason](https://www.hl7.org/fhir/encounter-definitions.html#Encounter.reason) is an array, not a single object.
2. Bundle.entry[11].resource.ofType(CarePlan).intent -- missing required element [CarePlan.intent](https://www.hl7.org/fhir/careplan-definitions.html#CarePlan.intent)

**Comment by psbrandt** [comment]
Here is an example of the first problem:

https://github.com/smart-on-fhir/generated-sample-data/blob/911c4856dc072519562ef9cb27e852957a31b22d/STU-3/SYNTHEA/Gusikowski_Lino_67.json#L268

**Comment by vlad-ignatov** [comment]
Those issues were fixed (long time ago) but we had some problems persisting CarePlan.intent values across nightly resets. I think everything should be working now.
